### ISSUE TITLE
Compass mapping update

### ISSUE THREAD

**Issue by Veraokulo** [The-Forbidden-Trove/tft-pricing-data#2]
please update compass mapping. Some of compasses have different mods wording. For instance:
1) "Your Maps contain an additional Tormented Heretic" in mapping and "Your Maps are haunted by an additional Tormented Heretic" in game
2) "Final Map Boss in each Map drops an additional Conqueror Map" in mapping and "An additional Conqueror Map drops on Completing your Maps (Tier 14+)" in game

**Comment by tojurnru** [comment]
fixed. feel free to make a pull request if there's any changes required in future.
